### ISSUE TITLE
[FEAT] DaffSwitchComponent

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1022]
# :bulb: Feature request

## Feature Name
DaffSwitchComponent

## The Desired Behavior
DaffSwitchComponent is form control that toggles the state of a single setting "on/off" by clicking it.

## Your Use Case
As an enduser, I'd like to be able to toggle between two states.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@xelaint can you post a link to the figma design for this component?

**Comment by xelaint** [comment]
@damienwebdev There isn't a design for this yet.
