### ISSUE TITLE
[Feature Request]: Strange Font-size on input[text]

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#105]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Currently, the input[text] and a few other elements have a font-size of `1.14285714rem` as reported by @lderrickable. I think this is something internally set by foundation.

## Expected behavior
Since we're not planning on using foundation long term for `foundation-demo` (though we should try to make another demo that uses foundation), we should standardize this into @daffodil/design.

## Additional todo
Remove any unneeded `font-size: 1rem` references that will automatically be applied, because of this feature request.

## Minimal reproduction of the problem with instructions
Look at an `input[type="text"]` and see that there's a goofy `font-size: 1.14285714rem` in the style cascade.

**Comment by xelaint** [comment]
Taken care of in #107
