### ISSUE TITLE
[FEAT] Improve Loading Behaviors on Cart State

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1082]
# :bulb: Feature request

## Feature Name
 Improve Loading Behaviors on Cart State

## The Desired Behavior
Resolution vs. Mutation vs. Loading
- Item
- Address
- Billing Address
- Shipping Address
- Shipping Methods
- Currently selected shipping method
- Payment methods
- Currently selected payment
- Promo code

## Your Use Case
As a designer, I'd like to be able to specify the loading UI more precisely.

Some Examples:
- Updating the quantity of a cart item should not trigger the loading state for the promo code container.
- Selecting a different shipping option does not need to trigger a load state on the whole cart summary container. The shipping line and totals line should be the only parts that show the 'ghost' state or a variation of it.
- Saving your address does not need to trigger a load state on the whole cart summary container.
- Removing an item from cart does not need to trigger load state on whole cart (only on item being removed).
- Adding a promo code to cart does not need to trigger a cart item's load state.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
I'll take this one.

@xelaint When you say
> Resolution vs. Mutation vs. Loading

Does that mean that you want different loading states for different operations? So updating the shipping address would be different than just fetching the shipping address?

Does the cart as a whole still have a loading state? Would that cause all the cart subfield loading states to also be loading? For example, triggering an entire cart load will fetch the shipping address; would that cause the shipping address loading state to be true in addition to the main cart loading state?
