### ISSUE TITLE
[FEAT] Remove GraphQL and @ngrx dependency requirements from main lib packages

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1093]
# :bulb: Feature request

## Feature Name

Daffodil Subpackaging

## The Desired Behavior

When I require a subpackage such as `@daffodil/contact/driver/hubspot`, I don't want to be forced to install additional deps such as `@ngrx` or `graphql` unless I actually need them.

## Your Use Case

As a developer, I would like to use Daffodil drivers without unecessary deps such as the state library.
As a developer, I would like to reference Daffodil models without pulling in unnecessary deps such as the state library or drivers.

Others:

</code></pre>
In the pursuit of being as modular as possible, we should separate the different layers of Daffodil into separate packages. This will prevent unnecessary dependencies as well as enforce layer decoupling.

**Comment by damienwebdev** [comment]
Closed buy #1091
