### ISSUE TITLE
[Testing] The in-memory testing driver needs better test cases

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#110]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>__

**Comment by griest024** [comment]
Many of the in-memory drivers actually have some decent test suites.
