### ISSUE TITLE
[FEAT] Handle Platform-Specific Errors

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1107]
# :bulb: Feature request

## Feature Name

Handle Platform-Specific Errors

## The Desired Behavior

I want to know when a Daffodil driver throws an error that is specific to my platform so I can handle some types of errors in special ways. Currently, Daffodil errors are very generic and not helpful.

## Your Use Case

I am using a Magento backend with the Authorize.net payment processor. When the backend throws a payment token expired error, I want to be able to handle that programmatically in my UI instead of just showing the generic error message.

Others:

The basic error flow goes like this:

1. A platform request throws an error.
2. The driver that made the request does the best it can to try and match the platform error to a known type of Daffodil error (object implementing `DaffError`).
3. The driver throws the `DaffError`.
4. The effect layer catches the `DaffError` and invokes an dependency injectable matcher function (`DAFF_CART_ERROR_MATCHER`) that returns a `DaffStateError`.
5. The effect layer ensures that the `DaffStateError` is serializable and dispatches a (somewhat unhygenic) failure action with the `DaffStateError` as a payload.
6. The reducer layer picks up the driver failure action and stores the `DaffStateError` object in the particular slice of state corresponding to the driver action type.

> Note: if the app dev needs to dispatch hygenic error specific actions, they should do so with their own effect.

relevant code:
```ts
interface DaffError extends Error {
  code: string;
  message: string;
}

interface DaffStateError {
  code: string;
  message: string;
}

const transformDaffErrorToStateError = (error: DaffError): DaffStateError => {
  return error;
}

const DAFF_CART_ERROR_MATCHER = new InjectionToken<typeof transformDaffErrorToStateError>('DAFF_CART_ERROR_MATCHER', {factory: () => transformDaffErrorToStateError})
```

**Comment by griest024** [comment]
@damienwebdev Do you think it would be better to serialize the state error object in the effect layer or in the reducer layer?

**Comment by damienwebdev** [comment]
Effects. Actions should be only handling primitives.
