### ISSUE TITLE
[BUG] DaffProduct.image should not be nullable

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1115]
# :bug: Bug report

## Current Behavior
DaffProduct.image is nullable.

## Expected Behavior
DaffProduct.image should not be nullable. It should be an empty array if it doesn't have images.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
@xelaint I'm not sure in which PR this was resolved, but it seems it was done at some point. Please verify and then close this issue if it's resolved.
