### ISSUE TITLE
[BUG] Cart state does not clear on order success.

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1141]
# :bug: Bug report

## Current Behavior
Cart state does not clear on order success.

## Expected Behavior
Cart state should be cleared on order success.

## Minimal reproduction of the problem with instructions
1. Add item(s) to cart
2. Go through checkout
3. Place order
4. Go to cart page (items should still be in cart)

## What is the motivation / use case for changing the behavior?
If an order has been successfully placed, there should be no more items in cart because the items have been purchased.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
Is this still occurring?

**Comment by xelaint** [comment]
@griest024 yes.
