### ISSUE TITLE
[FEAT] NGRX Current and Previous Operation States

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1154]
# :bulb: Feature request

## Feature Name

NGRX Current and Previous Operation States

## The Desired Behavior

I want Daffodil NGRX state to be very specific about the states of pending and completed operations. In general, I want to know if an operation on a piece of state is currently mutating or resolving, or has completed either successfully or with an error. I also want to know more specific states about particular special pieces of state when appropriate.

## Your Use Case

As an app dev, I would like to know the various operation states of all the Daffodil ngrx state slices.

As a Daffodil maintainer, I would like to be able to add arbitrary extensions to the general Daffodil state enums for particular feature slices. I would like these extensions to contribute to the higher-level feature area operation states in a meaningful way.

## Prior Work

```ts
import { DaffLoadingState } from '@daffodil/core/state';
/**
 * @daffodil/core/state
 */
export enum DaffStatefulEnum {
  /**
   * The default state, essentially indicating that no operations have occurred whatsoever.
   */
  Default = "Default",

  /**
   * This indicates that the most recent operation has failed. 
   */
  Error = "Error",

  /**
   * This indicates that the most recent operation has succeeded. 
   */
  Success = "Success",
}

// State heirarchy and priority.
// Mutating 
// Resolving
// Error
// Success
// Default


export enum DaffStatefulResovableEnum { 
  Resolving = 'Resolving'
}

export enum DaffStatefulMutableEnum {
  Mutating = 'Mutating',
}

export interface DaffStatefulObject<T> {
  daffState: T;
  daffStateMessage: string;
}


/**
 * @daffodil/cart/state
 */

export enum DaffCartExtensionState {
  Adding = 'Adding'
}

export enum DaffCartItemExtensionState {
  New = 'New'
}

export type DaffCartItemStates = DaffStatefulEnum | DaffStatefulMutableEnum | DaffCartItemExtensionState;

export interface DaffCartItemStateful extends DaffStatefulObject<DaffCartItemStates> {
  daffState: DaffStatefulEnum.Default,
  message: "Item successfully added!"
}
```

**Comment by damienwebdev** [comment]
Closed by #1302
