### ISSUE TITLE
[BUG] CI Build Failure

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1243]
# :bug: Bug report

## Current Behavior
The build is failing: https://github.com/graycoreio/daffodil/commit/0b7de2c1f5b954d48e0c23095bfeb7076997845c

## Expected Behavior
The build is passing.

## Minimal reproduction of the problem with instructions
See https://github.com/graycoreio/daffodil/commit/0b7de2c1f5b954d48e0c23095bfeb7076997845c

## What is the motivation / use case for changing the behavior?
QA

**Comment by griest024** [comment]
This is related to #1233, which is in process.

**Comment by griest024** [comment]
fixed 🤞
