### ISSUE TITLE
[BUG] CategoryLoadActions are switch mapped

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1282]
# :bug: Bug report

## Current Behavior
Multiple actions issued in series are being cancelled.

## Expected Behavior
Multiple actions should be concatMap or mergeMap.

## What is the motivation / use case for changing the behavior?
Trying to load multiple previews of different categories on a page. Only one category loads successfully.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
@xelaint is this for `DaffCategoryLoad` or `DaffCategoryPageLoad` or both?
