### ISSUE TITLE
[FEAT] Implement DaffState on the CategoryPageReducer

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1299]
# :bulb: Feature request

## Feature Name
Implement DaffState on the CategoryPageReducer

## The Desired Behavior
When we apply a filter on a category page, it should be a mutating state.

## Prior Work

Implement `daffState` on the `categoryPageConfigurationState`.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
@xelaint do you need individual categories to be mutating or is it sufficient that the entire category state is mutating?

**Comment by xelaint** [comment]
@griest024 I'm not entirely sure what the difference the two would make? @damienwebdev ?

**Comment by griest024** [comment]
For example, when a cart item quantity is updated, only that cart item enters a loading state. The other cart items are unaffected. Whereas when you add an item to the cart, the entire cart goes into a loading state.

**Comment by griest024** [comment]
> When we apply a filter on a category page, it should be a mutating state.

@xelaint what do you mean by `it`? Should the whole page go into a mutating state or just that filter checkbox? Should the app know specifically which filter is in a mutating state or is it enough to know that any filter is being mutated?

**Comment by xelaint** [comment]
> For example, when a cart item quantity is updated, only that cart item enters a loading state. The other cart items are unaffected. Whereas when you add an item to the cart, the entire cart goes into a loading state.

The item with the quantity being updated should be the only item that enters a loading state (this is already possible, correct?)

> > When we apply a filter on a category page, it should be a mutating state.
> 
> @xelaint what do you mean by `it`? Should the whole page go into a mutating state or just that filter checkbox? Should the app know specifically which filter is in a mutating state or is it enough to know that any filter is being mutated?

If a user applies a filter, I should expect the category-grid to display a mutating style, since the products in the grid will be changing.

**Comment by griest024** [comment]
> The item with the quantity being updated should be the only item that enters a loading state (this is already possible, correct?)

That is correct.

> If a user applies a filter, I should expect the category-grid to display a mutating style, since the products in the grid will be changing.

Got it. There are quite a number of things changing in category but this is in the works.

**Comment by griest024** [comment]
Waiting on `DaffStateable`.
