### ISSUE TITLE
[FEAT] Store category filter applied state in filter state object

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1361]
# :bulb: Feature request

## Feature Name

Store category filter applied state in filter state object

## The Desired Behavior

I want to have a filter's applied state tracked in the original filter object.

## Your Use Case

As an app dev, I would like to be able to back a filter checkbox with a single entity.

## Prior Work

Remove `DaffCategoryAppliedFilter`. Add `applied` to `DaffCategoryFilterOption`.

**Comment by griest024** [comment]
@damienwebdev Do you think `applied` should only be on a "stateful" extension of `DaffCategoryFilterOption` or should be be on the root model?

**Comment by damienwebdev** [comment]
I think this should be on the root model. While it is necessarily stateful, in theory, this is data that the platform should be providing to us, and thus determined by the driver. In the case of Magento, this looks like an oversight that we have to accommodate rather than a "good" arch.

**Comment by damienwebdev** [comment]
Fixed in https://github.com/graycoreio/daffodil/pull/1451
