### ISSUE TITLE
[PERF] Magento Get Category Request 

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1375]
# :turtle: Performance Issue

## Current behavior

The get category call in the magento driver has a number of apollo calls in series and parallel. Many of these queries might be unnecessary and some of them are uncacheable.

## Expected behavior

Drivers make the most minimal requests necessary and prefer cacheable requests.

## What is the motivation / use case for changing the behavior?

Perf

**Comment by griest024** [comment]
The request flow for external router category call is as follows:

a. External Router
b. External Router (cache)
    c. Category By Id
    d. Products By Category Id

Use this query to get product filters
```gql
query GetFilterTypesForCategory {
  __type (name: "ProductAttributeFilterInput") {
      inputFields {
        name
        type {
            name
        }   
      }
  }
}
```

**Comment by damienwebdev** [comment]
I'd like to tack on here a bit more information:

Assume each request is cacheable and takes 50ms.

## Scenario 1 - Load Category By URL with a well-normalized backend
### Agnostic to REST or GraphQl 

a. Resolve URI Type (`@daffodil/external-router`)
b.1. Category By URL (`@daffodil/category`) 
b.2. Products By Category ID (`@daffodil/product`)

Note that the latter two calls are able to be run in parallel.

> 3 Total calls -- 100ms.

## Scenario 2 - Load Category By URL with a backend that allows deeper calls into the Products of a Category
### Agnostic to REST or GraphQl 

a. External Router (`@daffodil/external-router`)
b. Category & Products By URL (`@daffodil/category`) 

> 2 Total calls -- 100ms.

## Scenario 3 - Load Route By URL and then category by Id with well-normalized backend 
### Platform Aware
##### GraphQl

a. External Router
b. External Router (cache)
c. Category By Id
d. Products By Category Id

> 4 Total calls -- 100ms.

##### REST
 
 a. External Router
 b. External Router
 c. Category By Id
 d. Products By Category Id
    
> 3 Total calls -- 150ms.

## Scenario 4 - Load Category By URL and then products by Id with well-normalized backend
### (not using external-router), e.g. Shopify, requires pre-knowledge of some routing structure
### Platform Aware

##### GraphQl 
a. Category By Url
b. Products By Category Id

> 2 Total calls -- 100ms.

##### REST
a. External Router (URL Resolution)
b. External Router (URL Resolution)
c. Category By Id
d. Products By Category Id
```

**Comment by damienwebdev** [comment]
Fixed by https://github.com/graycoreio/daffodil/pull/1451
