### ISSUE TITLE
Mocked images of products should come in with the GetProducts/GetProduct service call

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#140]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Image urls are currently hard coded in the ProductComponent in Foundation Demo.

## Expected behavior
Image urls should come back with the GetProducts/GetProduct service call, and should be store on redux state.

## What is the motivation / use case for changing the behavior?
Mocks and Stub data will more accurately represent how a production website will run.

**Comment by damienwebdev** [comment]
Closed by #150
