### ISSUE TITLE
Remove Google license from significantly modified source code.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#141]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Some of our files are based on, or drawn from examples in `@angular/material2`. Several of our animation files still include the original license from `@angular/material2`. 

## Expected behavior
We shouldn't include this license in the source, as it is significantly modified from Google's code. One could argue that we use the same "Style" of writing animations, but that's somewhat derived from the api's of `@angular/animations`.

## Minimal reproduction of the problem with instructions
See https://github.com/graycoreio/daffodil/blob/352ea7119115b7fee8de203de8b7dee3bca4945d/libs/design/src/molecules/accordion/animation/accordion-animation.ts as an example.

## What is the motivation / use case for changing the behavior?
We don't need their license in these files.  

## Other information
I would consider potentially adding the `@angular/material2` license into our "global" license file, as we definitely draw significant insight from the work of the `@angular/material2` team.

cc: @jelbourn If you could spare a moment, we would appreciate some guidance here, as we don't want to run awry of a license. Additionally, proper guidance would go a long way to making sure we do it the "right way".

**Comment by jelbourn** [comment]
I don't have anywhere to point, unfortunately.

**Comment by damienwebdev** [comment]
This was resolved in #300
