### ISSUE TITLE
Add styles to deal with directional icons in buttons with text

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#143]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Icons inside buttons with text is too close to the text. Padding needs to be added to add more space between text and icon.

## Expected behavior
Left padding on icon.

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@xelaint this should be pretty trivial to add support for in `daff-button` right?

**Comment by xelaint** [comment]
@damienwebdev yes, this is easy to implement.
