### ISSUE TITLE
[FEAT] Short Description property for DaffProduct

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1526]
# :bulb: Feature request

## Feature Name
Short Description property for DaffProduct

## The Desired Behavior
DaffProduct needs a `short description` property so endusers can have a short product summary as well as a full product description with the `description` property.

## Your Use Case
As a marketer, I'd like to be able to include a short description and full description about a product.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
Completed by: https://github.com/graycoreio/daffodil/pull/1631
