### ISSUE TITLE
[FEAT] DaffCartItem needs a URL that is resolvable.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1535]
# :bulb: Feature request

## Feature Name
DaffCartItem URLs

## The Desired Behavior
DaffCartItems should have a URL prop that can be used to reference the product that the DaffCartItem comes from. It should implement DaffLocatable.

## Your Use Case
As a customer, I want to navigate to the product that I added to my cart from my cart.

**Comment by griest024** [comment]
I'll take this one
