### ISSUE TITLE
[FEAT] Magento Breadcrumbs don't meet the DaffLocatable interface

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1536]
# :bulb: Feature request

## Feature Name
Magento Breadcrumb URL Resolution

## The Desired Behavior
Magento Breadcrumbs should use the `category_url_path` along with the `url_suffix` of their parent category with a leading slash appended.

## Your Use Case
As a user, I'd like to be able to navigate with breadcrumbs.

**Comment by griest024** [comment]
@damienwebdev I'll take this one
