### ISSUE TITLE
[BUG] Magento Add Bundle to Cart on v2.4.2 doesn't work

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1537]
# :bug: Bug report

## Current Behavior
When I try to add a bundled item to my cart using product_uid's I get the error:
```
GraphQL error]: Message: Please specify product option(s)., Location: undefined, Path: undefined
```

## Expected Behavior
I don't expect to get an error.

## Minimal reproduction of the problem with instructions
This is happening because we changed to using `product.uid` instead of `product.id` and the old `addBundledProductsToCart` doesn't handle `uid`. We need to use[ `addProductsToCart `](https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html)

## What is the motivation / use case for changing the behavior?
I'd like to be able to add bundle items to my cart.

## Environment

<pre><code>
Daffodil version: 0.32.0

**Comment by griest024** [comment]
I'll take this one
