### ISSUE TITLE
[FEAT] Magento External Router drivers should use the Magento Query Cache token

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1539]
# :bulb: Feature request

## Feature Name
Magento URL Resolver Query caching

## The Desired Behavior
As a developer, I expect URL Resolution to be cached by Magento.

## Your Use Case
Better performance.

**Comment by griest024** [comment]
Product get by URL needs to be cached

**Comment by damienwebdev** [comment]
Fixed by https://github.com/graycoreio/daffodil/pull/1551
