### ISSUE TITLE
[FEAT] Canonical URL Service

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1632]
# :bulb: Feature request

## Feature Name
Canonical URL Service

## The Desired Behavior
I want to be able to upsert and remove a canonical URL for a document.

## Your Use Case
As a developer, I have to be able to change the canonical URL of a document easily. Currently, with Angular v12, there's no "nice" way to do this.

## Prior Work
Web.dev has a nice article here -- https://web.dev/canonical/

Additionally, Lighthouse has an audit that validates canonicals too.

## Possible Implementation

I think this warrants a new package called `@daffodil/seo` as that is the chief purpose of this feature.

```ts
export interface DaffCanonicalService {
  upsert(url :string): void;
  remove(): void;
}
```

## Environment

<pre><code>
Daffodil version: 0.36.1
Angular version: 12.0.0

**Comment by griest024** [comment]
So we should handle the edge case where a canonical link tag already exists in the page?

**Comment by damienwebdev** [comment]
I think so yes.
