### ISSUE TITLE
[BUG] `@daffodil/external-router` breaks IE11 compatability

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1644]
# :bug: Bug report

## Current Behavior
There are several aspects of the `@daffodil/external-router` that are currently incompatible with IE11.

## Expected Behavior
The entire daffodil framework works with IE11.

## Minimal reproduction of the problem with instructions
https://github.com/graycoreio/daffodil/blob/develop/libs/core/routing/src/uri/truncation/query-fragment.ts depends on the URL constructor.

https://github.com/graycoreio/daffodil/blob/develop/libs/core/routing/src/uri/truncation/file-extension.ts depends on regex groups.

## What is the motivation / use case for changing the behavior?
Backwards compatability.

## Environment

<pre><code>
Daffodil version: 0.37.0
Angular version: ^10.0.0

**Comment by lderrickable** [comment]
@damienwebdev how can you tell that regex groups aren't supported on IE11?

**Comment by damienwebdev** [comment]
I was looking at https://caniuse.com/?search=regex%20group, but I didn't do an acceptance test to see if that was correct.
