### ISSUE TITLE
[FEAT] Update dgeni path to `/docs`

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1678]
# :bulb: Feature request

## Feature Name
Update 'guides' path to 'docs'

## The Desired Behavior
Update dgeni path to `/docs`

## Your Use Case
As an enduser, I'd like the path of the Daffodil Docs to be consistent with 'docs' naming convention.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by AnnieMi888** [comment]
#2641

**Comment by xelaint** [comment]
@griest024 is this done?

**Comment by griest024** [comment]
Yes, closed by #2824
