### ISSUE TITLE
[FEAT] Products need the magento_product attribute field

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#1682]
# :bulb: Feature request

## Feature Name
Products need the magento_product attribute field

## The Desired Behavior
The `transformMagentoProductResponse` attaches the `magento_product` to each product returned.

## Your Use Case
Originally, it was thought this wouldn't be needed, because any `extra_attributes` added to the Magento Product query could just be accessed through injected transformers. However, as I was working through extracting the configurable product feature out of `@daffodil/product/driver/magento` (and into `@daffodil/product/configurable/driver/magento`), it became evident that this will become a problem when working with `upsell` or `related` products. Because `upsell`, `related`, and `configurable` products will all be injected into the main product driver, it isn't possible to transform a configurable, upsell product without creating a dependency between the two. Either we would need to reference `magentoProduct.upsell` from within the configurable product feature, or we would need a subpackage within the `upsell` feature whose purpose is just to transform configurable, upsell products. This problem is solved by including a `magento_product` to each product in `DaffProductDriverResponse`.

**Comment by griest024** [comment]
If we had injectable transforms for the product preview, couldn't the configurable inject its transform to that? Then when the injected related transform invokes the product preview transforms it will get the configurable transform logic without being coupled to the configurable package.

**Comment by lderrickable** [comment]
makes sense to me. I'll open a PR for that
