### ISSUE TITLE
[PERF] Magento Category Page Query loads related products, resulting in massive bandwidth consumption.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1723]
# :turtle: Performance Issue

## Current behavior
Currently, after the merge of https://github.com/graycoreio/daffodil/pull/1626 category pages with the Magento driver load a tremendous amount of data (Magento store-dependently) as a result of `related_products` and `upsell_products`.

## Expected behavior
We shouldn't be pulling these fields on category product list requests.

## Minimal reproduction of the problem with instructions
Use the Magento driver and submit a `getByUrl` or `get()` and inspec t the response body.

## What is the motivation / use case for changing the behavior?
Low-bandwidth considerations for performant PWAs.

**Comment by griest024** [comment]
configurable, composite, related and upsell all need their own packages for this change to be possible.

**Comment by damienwebdev** [comment]
This is closed by a combination of PRs:

https://github.com/graycoreio/daffodil/pull/1690
https://github.com/graycoreio/daffodil/pull/1681
https://github.com/graycoreio/daffodil/pull/1707
