### ISSUE TITLE
[FEAT] SEO Meta Service

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1732]
# :bulb: Feature request

## Feature Name

SEO Meta Service

## The Desired Behavior

There needs to be a way to update and remove meta tags.

## Your Use Case

- As an app dev, I would like to manage the meta title of the page.
- As an app dev, I would like to manage the meta description of the page.

#### Arbitrary Meta Tags
```ts
interface DaffMetaInterface {
  upsertMetaTag(name: string, content: string): void;
  removeMetaTag(name: string): void;
}
```

#### Specific Meta Tags
```ts
interface DaffMetaInterface {
  upsertMetaTitle(content: string): void;
  removeMetaTitle(): void;
  upsertMetaDescription(content: string): void;
  removeMetaDescription(): void;
  // etc.
}
```

**Comment by griest024** [comment]
@damienwebdev @lderrickable Which of the above interfaces do you prefer?

**Comment by damienwebdev** [comment]
Strong preference for the former for arbitrary meta tags.

**Comment by griest024** [comment]
> I think we use the original angular types as well, but with better function names.

[This type](https://angular.io/api/platform-browser/MetaDefinition)?

**Comment by griest024** [comment]
@damienwebdev Do we need more than just `name` and `content`?

**Comment by damienwebdev** [comment]
Yes. We can't predict precisely what end-users will want to do. So, it makes the most sense to abide by the original browser specification as possible.

I think merely wrapping the Angular service with what we think is a clearer API is better.

**Comment by griest024** [comment]
How would you cache the meta tags? Key by `name`?

**Comment by griest024** [comment]
> I think merely wrapping the Angular service with what we think is a clearer API is better.

By this do you mean just changing the method names or changing the types as well?
