### ISSUE TITLE
[FEAT] Release Tool Should Cleanup on Error

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1768]
# :bulb: Feature request

## Feature Name

Release Tool Should Cleanup on Error

## The Desired Behavior

When the release tool errors, for example during the build, it should still perform cleanup actions.

## Your Use Case

As a maintainer, I don't want to have to manually delete the temporary release branch when the release task fails.

**Comment by damienwebdev** [comment]
Duplicate of #1139
