### ISSUE TITLE
feat(design): move loader into design

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#177]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
https://www.lottiefiles.com/share/xQqlIE

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
@xelaint I moved the loading-icon into the design module, but Damien was talking about making our own loading gif so we didn't need to depend on font awesome

**Comment by xelaint** [comment]
@lderrickable here's the lottie version (https://www.lottiefiles.com/share/xQqlIE), @damienwebdev can convert this to a css version.
