### ISSUE TITLE
[FEAT] `DaffModelFactory` should return a class instance

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1778]
# :bulb: Feature request

## Feature Name

`DaffModelFactory` should return a class instance

## The Desired Behavior

When I create a model using a factory, I want that model to be of the mock class type.

## Your Use Case

As a maintainer, I want to be able to check object type: `expect(...).toEqual(jasmine.any(MockModelClass)`

## Prior Work

```ts
// use Object.assign to preserve the object's class
    return Object.assign(new this.type(...this._instantiationArgs), partial);
```

**Comment by griest024** [comment]
Not sure this is definitely a feature we want

**Comment by damienwebdev** [comment]
I'm fairly confident it isn't. The instance should be a simple JSON object of the data, not a true "instance" with functions on it.
