### ISSUE TITLE
[BUG] Dgeni generated docs are unsanitized

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#1798]
# :bug: Bug report

## Current Behavior
Dgeni generated docs are unsanitized

## Expected Behavior
Dgeni generated docs should be sanitized

## Minimal reproduction of the problem with instructions
http://next.daff.io/api/design/DaffInputComponent

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
sanitizing the docs will remove links and stuff. We need to write a custom sanitizer that will handle these specific behaviors
