### ISSUE TITLE
[FEAT] Code Block Sanitizer for Docs

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1800]
# :bulb: Feature request

## Feature Name

Code Block Sanitizer for Code Blocks

## The Desired Behavior

I want links and other relevant info to be preserved.
I want HTML elements and other code content to be sanitized.

## Your Use Case

As an app dev, I want links in API docs to work.
As an app dev, I want to see code block content, not have it rendered in daff.io.

## Prior Work

#1798

**Comment by damienwebdev** [comment]
Blocked by https://github.com/graycoreio/daffodil/issues/2641
