### ISSUE TITLE
[BUG] CI does not run a full test after running a full build

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1822]
# :bug: Bug report

## Current Behavior

When the conditions for a full build are met, a full test will not necessarily run.

## Expected Behavior

If a full build is run, a full test should be performed.

## Minimal reproduction of the problem with instructions

Change `angular.json` and run a PR CI

## What is the motivation / use case for changing the behavior?

Testing code that changed. Generate coverage reports that cannot be restored from cache.

**Comment by damienwebdev** [comment]
Closed by #2420 #2419 #2418
