### ISSUE TITLE
[BUG] v12 Fails During Build from Multiple `ngcc` Processes

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1833]
# :bug: Bug report

## Current Behavior

`npx lerna run build` causes

```An error occurred during the build:
Error: ngcc is already running at process with id ####.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
```

## Expected Behavior

I can run builds.

## Minimal reproduction of the problem with instructions

```
rm -rf dist
npx lerna run build
```

## Environment
This is a bug specific to Angular v12 #1832

**Comment by griest024** [comment]
> parallel builds are currently not supported with NGCC

https://github.com/angular/angular/issues/32431#issuecomment-526837804

well that sucks. :/ Do we just have to disable parallelization for our builds?

**Comment by griest024** [comment]
Although... `ngcc` is supposed to support parallel builds:
```
--async                            Whether to compile asynchronously. This
                                         is enabled by default as it allows
                                         compilations to be parallelized.
                                         Disabling asynchronous compilation may
                                         be useful for debugging.
                                                       [boolean] [default: true]
```

Maybe the auto-`ngcc` that is performed during builds is explicitly serialized? Not sure how we could change this behavior.

Another possibility is to `ngcc` after every build: `build: "ng builb lib --prod && ngcc --async`.

**Comment by damienwebdev** [comment]
This is only possible to be remedied by the compiler-cli team. We ended up choosing to disable parallelization for the time being.

Apparently, this problem may just go away with Angular 16 since ngcc is gone.

https://github.com/angular/angular/issues/49811
