### ISSUE TITLE
[BUG] `daffPrecision` exhibits infinite loops when `number` is `NaN` or `Infinity`

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1844]
# :bug: Bug report

## Current Behavior
`daffPrecision(NaN)`
`daffPrecision(Infinity)`

## Expected Behavior
I expect the function to terminate in a reasonable manner.

**Comment by griest024** [comment]
`daffPrecision` is not an exported function. This bug fix will target the `daffDivide` function, officially.
