### ISSUE TITLE
[FEAT] Better tests for randomized functions

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1858]
# :bulb: Feature request

## Feature Name

Better tests for randomized functions

## The Desired Behavior

Functions that include `Math.random()` should have the seed controlled better test the behavior of the function.

## Your Use Case

As a Daffodil maintainer, I would like to test random functions well.

**Comment by damienwebdev** [comment]
After discussion with @griest024 this is likely not in the scope of Daffodil. If you want better control over your randomness, please use [@faker](https://github.com/faker-js/faker)
