### ISSUE TITLE
Feature Request: daff-logo should implement "colorable".

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#191]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

**Comment by xelaint** [comment]
@damienwebdev The `Daffodil` text should be the only part of the logo that is colorable.

**Comment by damienwebdev** [comment]
@xelaint I agree. My only issue is that I don't want naming to conflict with the `DaffColorable` interface, so `[color]` may be a bit confusing. Any suggestions for an `@Input()` name? Perhaps `[color]` won't be too confusing if we document it well enough.

**Comment by xelaint** [comment]
Would `theme` work? (`theme=light` and `theme=dark`) I think there would only be two logo instances...`dark-logo` for light theme and `light-logo` for dark theme.

`logo-icon` would not matter on theming.
