### ISSUE TITLE
[BUG] `DaffModelFactory` Type is Required

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1939]
# :bug: Bug report

## Current Behavior

The type constructor param of the `DaffModelFactory` is required.

## Expected Behavior

`DaffModelFactory` should be more flexible and that arg should be optional.

## What is the motivation / use case for changing the behavior?

Sometimes models will just override the `create` method for more custom behavior; the `type` param is never used in this case.

**Comment by damienwebdev** [comment]
Closed by #1942
