### ISSUE TITLE
[BUG] `$black` variable is missing from `daff-button` theme functions in ng11

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#1940]
# :bug: Bug report

## Current Behavior
Currently, I can't set use the design library on latest Angular 11.

## Expected Behavior
I expected the design library to work.

## Minimal reproduction of the problem with instructions
I was following the [getting started guide](https://github.com/graycoreio/daffodil/blob/develop/libs/design/guides/getting-started.md) and I got the following error when I added the theme: 

```
Error in node_modules/@daffodil/design@0.39.9/daff-theme.scss (2186:18)
Undefined variable.
╷
2186 │ 0 3px 5px rgba($black, 0.12),
│ ^^^^^^
╵
../node_modules/@daffodil/design@0.39.9/daff-theme.scss 2186:18 daff-raised-button-theme-variant()
../node_modules/@daffodil/design@0.39.9/daff-theme.scss 2381:3 daff-button-theme()
../node_modules/@daffodil/design@0.39.9/daff-theme.scss 3603:2 daff-theme()
../~/src/styles.scss 4:1 root stylesheet
```

[Stackblitz](https://stackblitz.com/edit/ng11-daffodil-design-yguhf4?file=src%2Fstyles.scss)

## What is the motivation / use case for changing the behavior?
I tried to use the design library.

## Environment

<pre><code>
Daffodil version: 0.39.9
Angular version: 11.2.14
</code></pre>

**Comment by xelaint** [comment]
Fixed via #2173
