### ISSUE TITLE
The demo's checkout module should be lazy-loaded.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The checkout module loads regardless of whether or not you ever hit `checkout`.

## Expected behavior
I expect to only have to load the code I need.

## Minimal reproduction of the problem with instructions
Visit the demo site, see that all the checkout code is loaded when visiting the site for the first time.

## What is the motivation / use case for changing the behavior?
Performance.

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xxGizmoCodexx** [comment]
Hi @damienwebdev 
Is this an issue that still needs looking at?
Not sure if it was resolved in the previous PR attempt

**Comment by damienwebdev** [comment]
Yes! If you'd like to take a stab at it, please do! It should hopefully be pretty easy, but if you get stuck please feel free to hop in discord and ask questions!

**Comment by xxGizmoCodexx** [comment]
Ok great
In the spirit of `Hacktoberfest` I would like to attempt to fix this if you wouldn't mind assigning it to me 💻 😃

**Comment by xxGizmoCodexx** [comment]
@damienwebdev #2201 should fix this 👍
