### ISSUE TITLE
Feature Request: Support i18n translations for daffio

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#202]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, we don't support translations to different languages other than English.

## Expected behavior
We should support languages other than English (e.g. CN to start).

## Minimal reproduction of the problem with instructions
1. Only know CN
2. Like the idea of daffodil
3. Be unable read docs or understand daffodil's benefits

## What is the motivation / use case for changing the behavior?
We'd like to provide more users the ability to use daffodil.

**Comment by AnnieMi888** [comment]
how to do translation and docs generation
