### ISSUE TITLE
Add Creation of the Order Object to the checkout process

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#203]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When an order is placed, the page is just redirected to the `thank-you` page.

## Expected behavior
When an order is placed, the `Cart` should be copied onto another object on checkout state called `Order`, and the `Cart` should be cleared. Navigation to the `thank-you` page should have a guard that checks that the `Order` was successfully created.

## Minimal reproduction of the problem with instructions
Place an order.

## What is the motivation / use case for changing the behavior?
A better checkout process.

Others:
This could be split up into two pull requests. One for adding the `Order` state, and one for adding the routing guard logic.

**Comment by damienwebdev** [comment]
Closed by #209
