### ISSUE TITLE
[BUG] CI crashes when source branch contains a quote character

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2042]
# :bug: Bug report

## Current Behavior

When the PR branch name contains a `'` or `"`, the `Set Code Climate PR Vars` step fails with an unterminated quote character.

## Expected Behavior

CI does not crash

## Minimal reproduction of the problem with instructions

https://dev.azure.com/graycore/Daffodil/_build/results?buildId=7671&view=logs&j=93920417-eedc-5d0d-3fdd-d383262f4173&t=fb64ba39-b2b0-5175-8956-0ddbdfddad70

## What is the motivation / use case for changing the behavior?

Others:

</code></pre>
This is most likely an azure bug, `System.PullRequest.SourceBranch` should automatically escape special chars. We can probably ignore this for now, as we will soon (TM) switch to GH actions.

**Comment by damienwebdev** [comment]
I'm going to assume that this is closed by #2419
