### ISSUE TITLE
The current implementation of RouteGuards breaches SRP.

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#205]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The CartLoadGuard is currently implemented as a routing guard, but that isn't really what it does. It ensures that a valid Cart is fetched before the real routing guard (CheckoutGuard) is called.

## Expected behavior
The CartLoadResolver service is called before the CheckoutGuard to load a defined Cart before calling the CheckGuard.canActivate method. If the call for the Cart errors out, the CartLoadResolver should redirect to `/cart` itself.

## What is the motivation / use case for changing the behavior?
So that services act in accordance with their intended purpose.

**Comment by damienwebdev** [comment]
So, I agree, a resolver-like functionality makes sense here, but I'd first like to outline some 
requirements that nicely map to business use-cases. Once we do this, I feel a better implementation will become more clear.

1. As a user, when I visit the checkout page and I'm waiting for my cart to be returned from the API, I should see some kind of loading indicator.
2. As a user, when I visit the checkout page directly and my cart returns successfully -- **if there are no items in my cart**, I should be redirected to the cart page.
3. As a user, when I visit the checkout page directly, and my cart returns successfully, **if there are items in my cart**, I should see some kind of checkout flow.
4. As a user, when I visit the checkout page directly, and the cart API fails, I should be redirected to the cart page, and see some kind of error state.
