### ISSUE TITLE
Handle changeDetection and directive/component declaration correctly

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#213]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Elements without `@Inputs/@Outputs` are used as components.

## Expected behavior
Refactor components without `@Inputs/@Outputs` (that supplement elements) need to be changed to Directives.

## Minimal reproduction of the problem with instructions

- [x] `proceed-to-checkout`
- [x] `view-cart`
- [x] `accordion-item-title`
- [x] `accordion-item-content`
- [x] `callout-body` (change to callout-subtitle)
- [x] `callout-title`
- [x] `feature-body`
- [x] `feature-icon`
- [x] `feature-title`
- [x] `hero-title`
- [x] `hero-subtitle`
- [x] `list-item-icon`
- [x] `list-item-subheader`

## What is the motivation / use case for changing the behavior?
A `directive` supplements the abilities of an element
A `component` is a stand-alone element

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
@damienwebdev this issue can be closed then?

**Comment by damienwebdev** [comment]
I do want to get @lderrickable's thoughts on this too, as he was the one who touched the code last, and it's important that we're all clear on why we need the revert/the challenges we face with changeDetection in the future.

**Comment by lderrickable** [comment]
I think this issue should become something like "Handle changeDetection and directive/component declaration correctly", because with what Damien has uncovered, most of the attribute components that we have in design and demo should actually be directives now. So anything that is attached via an attribute and doesn't have inputs or outputs should be a directive.

**Comment by xelaint** [comment]
@lderrickable @damienwebdev I updated the description and included a list of components that need to be updated. Lmk if I missed anything.
