### ISSUE TITLE
Move add-to-cart-notification modal into cart module

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
Wait for #192 to merge.

**Comment by lderrickable** [comment]
I looked into this, and I don't think it should go in cart module. At its core, it's a UI component, and it needs to use `@daffodil/design` components like DaffButton. And I don't think we want `@daffodil/cart` to depend on `@daffodil/design`. What you guys think? @xelaint @damienwebdev

**Comment by lderrickable** [comment]
> I looked into this, and I don't think it should go in cart module. At its core, it's a UI component, and it needs to use `@daffodil/design` components like DaffButton. And I don't think we want `@daffodil/cart` to depend on `@daffodil/design`. What you guys think? @xelaint @damienwebdev

nvm. I misunderstood the issue
