### ISSUE TITLE
Demo's `daff-logo` looks wrong in safari, but works on daffio.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#219]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The Demo logo has black petals in Safari

## Expected behavior
The Demo logo should look correct, and the same in every browser.

[daffodil logos.zip](https://github.com/graycoreio/daffodil/files/2803622/daffodil.logos.zip)

## Minimal reproduction of the problem with instructions
Load up the `demo` in Safari and look at the logo.

## What is the motivation / use case for changing the behavior?
Branding

**Comment by xelaint** [comment]
@damienwebdev 

[daffodil logos.zip](https://github.com/graycoreio/daffodil/files/2803618/daffodil.logos.zip)

**Comment by xelaint** [comment]
@damienwebdev zip file added.
