### ISSUE TITLE
[BUG] Using Auth triggers SSR Errors

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2247]
# :bug: Bug report

## Current Behavior
```
ERROR w [Error]: The DaffServerErrorStorageService always throws an error.                                                                                                                    │
│     at e1.throwError (file.js:1267:25993)                                                                                             │
│     at e1.getItem (file.js:1267:25902)                                                                                                │
│     at v.getAuthToken (file.js:551:612985)                                                                                            │
│     at file.js:551:609814                                                                                                             │
│     at file.js:551:58311                                                                                                              │
│     at g._next (file.js:551:56013)                                                                                                    │
│     at g.next (file.js:551:45700)                                                                                                     │
│     at g._next (file.js:551:46014)                                                                                                    │
│     at g.next (file.js:551:45700)                                                                                                     │
│     at I._subscribe (file.js:551:54183) {                                                                                             │
│   recoverable: false,                                                                                                                                                            
```

## Expected Behavior
No error during SSR. More likely, no auth at code should run during SSR.

## Minimal reproduction of the problem with instructions
1. Add Auth State Module
2. Add Angular Universal

## What is the motivation / use case for changing the behavior?
SSR!

## Environment

<pre><code>
Daffodil version: [v0.47.3](https://github.com/graycoreio/daffodil/releases/tag/v0.47.3)
damien@DESKTOP-N7ABP4H:~/frontend$ npx ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.6
Node: 16.10.0
Package Manager: npm 7.24.0
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, elements
... forms, localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.2.6
@angular/language-service       13.2.7
@nguniversal/common             13.1.1
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.4.4
webpack                         5.74.0</code></pre>

**Comment by griest024** [comment]
I assume we solve this the same way that we did with cart? Catch the server side storage error and dispatch a server side action?

**Comment by damienwebdev** [comment]
I assume that's correct. I'm pretty sure that the state change is to wind up in a "guest" state.

**Comment by griest024** [comment]
yes I agree. There's no way a customer can be logged in if we don't have access to localstorage. Feel free to assign to me if you want
