### ISSUE TITLE
[FEAT] auth redirect effects

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2275]
# :bulb: Feature request

## Feature Name

auth redirect effects

## The Desired Behavior

- [ ] When the customer is logged in, I would like them to be redirected to the page from which they came.
- [x] When a customer is logged out, they should be redirected to the login page.

**Comment by griest024** [comment]
take care not to `switchMap` on the `route.queryParamMap` observable when implementing the redirect

**Comment by griest024** [comment]
Tracking the redirect URL is not so simple. Should we just track *all* URL changes and save in state or should it be more transient than that?

**Comment by xelaint** [comment]
@griest024 I think customer should also be redirect to the page from which they came from if they choose to log out (i.e. from the account menu in the nav)

**Comment by griest024** [comment]
> @griest024 I think customer should also be redirect to the page from which they came from if they choose to log out (i.e. from the account menu in the nav)

Wouldn't they just stay on their current page, unless they were inside a member only section?

**Comment by damienwebdev** [comment]
This is now possible as a result of https://github.com/graycoreio/daffodil/pull/2408.
