### ISSUE TITLE
(feat: image-list) Vertical/Horizontal Support

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#23]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The `image-list` only support horizontal directionality. 

## Expected behavior
The `image-list` can be directed either vertically or horizontally.

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
I would like to use a vertical `image-list` in the `image-gallery` on desktop.

## Environment

<pre><code>
Daffodil version: 1.0.0-alpha
</code></pre>

**Comment by xelaint** [comment]
@lderrickable will this get done in v1.0.0 too?

**Comment by lderrickable** [comment]
> @lderrickable will this get done in v1.0.0 too?

oops, missed this comment. Yes, Damien is working on it now

**Comment by lderrickable** [comment]
addressed here: https://github.com/graycoreio/daffodil/pull/129
