### ISSUE TITLE
[BUG] Demo version: failing to add items to cart

### ISSUE THREAD

**Issue by seyuf** [graycoreio/daffodil#2337]
Adding items to cart is not working on the demo app.
**"Cannot read properties of undefined (reading 'items')"**

## Current Behavior

Nothing happens when click on add to cart on a product page

## Expected Behavior
Product added to cart

## Environment

Daffodil version: 0.51.1
Angular version: 13.3.0 
 

Others:
The issue : **"Cannot read properties of undefined (reading 'items')"**
From: [libs/cart/driver/in-memory/src/backend/cart-items/cart-items.service.ts#L126](https://github.com/graycoreio/daffodil/blob/d5eea7ec27cad74a355f969835b8ed37956c099d/libs/cart/driver/in-memory/src/backend/cart-items/cart-items.service.ts#L126)

**Comment by griest024** [comment]
probably caused by #2329

**Comment by griest024** [comment]
could not repro with latest daffodil
