### ISSUE TITLE
[FEAT] cart totals should be a dict

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2359]
# :bulb: Feature request

## Feature Name

cart totals should be a dict

## The Desired Behavior

I want to easily look up cart totals by type.

## Your Use Case

As an app dev, I don't want to have to do `cart.totals.find` to get a specific total type.

**Comment by griest024** [comment]
if order matters, it should be a field on the total object

**Comment by damienwebdev** [comment]
Agreed, however I think we were likely relying upon the ordering given to us by the api. What are your thoughts on this generally? 

If we rely on client-side ordering, we wind up calling `sort` very often across many many devices, which is computationally wasteful. I think I'd prefer to only use server-side ordering. but I'd like to understand the use-case for wanting to look up a particular total on the client.

**Comment by griest024** [comment]
ideally we would be memoizing the selector so we would sort only once per cart update. From a purely performance perspective, I favor the dict option since `totals.find` appears at least 8 times in our codebase.

**Comment by griest024** [comment]
> Agreed, however I think we were likely relying upon the ordering given to us by the api. What are your thoughts on this generally?

We should rely on this ordering. So we set the `order` field according to the array position for platforms that don't provide an explicit `order` field.

**Comment by griest024** [comment]
given that there needs to be support for multiple discount totals, a total dict is not straightforward

**Comment by griest024** [comment]
multiple discounts should have its own field on cart, a "total" implies an aggregation of all discounts into a single value
