### ISSUE TITLE
[FEAT] Add sponsorship link to daff.io

### ISSUE THREAD

**Issue by AnnieMi888** [graycoreio/daffodil#2435]
Add a new item as "sponsorship" or "donation" to the navigation in the header. Use the link https://github.com/sponsors/graycoreio for the new menu item

**Comment by damienwebdev** [comment]
@AnnieMi888 this request is quite vague, can you clarify what you mean?

**Comment by AnnieMi888** [comment]
![image](https://github.com/graycoreio/daffodil/assets/121879281/7c2609b0-b0d2-4016-a921-ce94a38dbcb7)

We should add a donation menu item to navigation on the website, see picture. The link should lead to https://github.com/sponsors/graycoreio
