### ISSUE TITLE
[FEAT] Update CSS animations to only animate properties in the GPU

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2446]
# :bulb: Feature request

## Feature Name
Update CSS animations to only animate properties in the GPU

## The Desired Behavior
CSS animations should utilize properties/styles that are in the GPU to reduce implicit compositing and lessen memory. `transform` and `opacity` should ideally be the only properties that are animated.

TODO:
- [x] Button
- [x] Media Gallery
- [x] List
- [x] API List
- [x] Type Label Mixin

## Your Use Case
As a developer, I should not be animating styles that are not in the GPU.

## Prior Work
https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108
https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shadow0500** [comment]
### By using GPU-accelerated properties and limiting the number of properties that are animated, you can reduce the amount of memory used by the animation and improve its performance. You can also consider using the will-change property to inform the browser that an element will be animated, which can help optimize its performance.

Overall, optimizing CSS animations for GPU acceleration can improve the user experience and make your application feel more responsive

**Comment by damienwebdev** [comment]
Touched by https://github.com/graycoreio/daffodil/pull/2583

**Comment by xelaint** [comment]
TODO:
- [ ] Accordion
- [ ] API List
- [ ] Type Label Mixin
