### ISSUE TITLE
[BUG] User is logged out for auth check network failures

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2460]
# :bug: Bug report

## Current Behavior

As a user, when the network request for getting my cart fails due to a poor internet connection, I am incorrectly logged out.

## Expected Behavior

As a user, I should *only* be logged out when auth check fails due to an unauthorized,/unauthenticated error

**Comment by shadow0500** [comment]
@griest024  can I work on this issue?

**Comment by griest024** [comment]
Yes
