### ISSUE TITLE
[FEAT] Link to API docs from markdown guides

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2474]
# :bulb: Feature request

## Feature Name

Link to API docs from markdown

## The Desired Behavior

`@daffodil/tools-dgeni` replaces exported symbol links in markdown with `daff.io` links.

## Your Use Case

As a daffodil dev, I want to be able to write API symbols in markdown files and have these replaced by the appropriate `daff.io` link to the symbol.

## Prior Work

dgeni will currently correctly transform links of the form `/libs/<package>/<symbol>` but this is rather cumbersome. Ideally *any* public API symbol written in code blocks would be transformed to the appropraite link.

**Comment by griest024** [comment]
@hanmangokiwi is this something you're interested in tackling?

**Comment by shadow0500** [comment]
@griest024 you can use this approach 
``` code 
import { Dgeni, Plugin } from '@daffodil/tools-dgeni';

export class LinkToApiDocsPlugin implements Plugin {

  constructor(dgeni: Dgeni) {
    super(dgeni);

    // Register a processor that will replace links to symbols with links to daff.io.
    const linkToApiDocsProcessor = (doc: Document, node: Node) => {
      if (node.type === 'link' && node.attributes['href'].startsWith('daffodil')) {
        // Replace the link with the daff.io link for the symbol.
        node.attributes['href'] = `https://daff.io/docs/${node.attributes['href']}`;
      }
    };

    dgeni.addProcessor('linkToApiDocs', linkToApiDocsProcessor);
  }
}
```

**Comment by xelaint** [comment]
@griest024 is this still relevant?

**Comment by griest024** [comment]
Yes. Many times we will need to link to API symbols in docs (guides and other API docs). These links should be clickable and navigate to the relevant page of the API docs

**Comment by griest024** [comment]
this can be supported with a slightly goofy `/libs/<package>/<symbol>` syntax. It would be cool to have code blocks that match any API symbol to automatically get replaced with the link but that requires some interpackage dgeni deps.
