### ISSUE TITLE
[BUG] Cart Resolution during logout exhibits race conditions

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2477]
# :bug: Bug report

## Current Behavior
While using the Magento cart driver, I saw errors in my shop's logs that indicated authorization problems and access issues on carts.

The specific errors were:

- The current customer isn't authorized
- The current user cannot perform operations on cart ""*"""
- Cart does not contain products. 

Importantly, the "The current user cannot perform operations on cart" all had legitimate looking cart ids, implying that something else strange occurred. I've noticed in the past that cart resolution and the logout "state clear" associated with the Magento driver is isn't particularly stable. Sometimes, the logout occurs and the `DAFF_CART_ID` of the authenticated user is deleted from storage, other times, it returns in a `The current user cannot perform operations on cart` because the `DAFF_CART_ID` wasn't deleted until after the state clear.

## Expected Behavior
I expect to have less of these in my logs than i do now. 

I also expect that when I logout, i'm guaranteed to delete the user's `DAFF_CART_ID` before a state clear occurs.

## What is the motivation / use case for changing the behavior?
Stable user-experience when logging out.

## Environment

<pre><code>
Daffodil version: 0.60.1
Angular version: 13
</code></pre>

## Additional information

Importantly, the re-resolution of a cart upon logout is also an interesting and related problem given the state clear feature required by Apollo drivers. I think the work that @griest024 is doing to put "forced" cart resolution upon page view behind a flag is probably helpful here, but we should still both flows to work.

**Comment by shadow0500** [comment]
@damienwebdev  you can correct me if I am wrong :
I also faced such kind of issue and I  resolved that issue by following the below step .
- create a function name logout user and call the rest of 3 function inside this function and after that create 3 other functions delete cartId which make sure when the user logout  cartId should be deleted.
- After that create a function name clear session which make sure that the user session should be cleared after deleting the user cartId and after that create a function name perform logout which make sure that after successfully completion of the above function , user session must be destroyed and the user logout successfully.
-  At last we check if the user is logged in then call the logout user function which automatically call rest of the three task .
``` code 


function logoutUser() {
   
    deleteCartId();
    clearSession();
    performLogout();
}


function deleteCartId() {

}

function clearSession() {

}


function performLogout() {

}


if (loggedIn) {
    logoutUser();
}
```
