### ISSUE TITLE
[FEAT] Add a loading state when images in a media-gallery or thumbnail are "empty"/loading.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#25]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When images are "empty"/loading, we currently just don't show the component. 

## Expected behavior
When images are "empty"/loading, we should show a "loading"-like state which is just static gray boxes. This will prevent the page from content jumping as much and will make for a better user experience. 
![13bdedfe-f631-4611-a487-65a9cd1c59f5](https://user-images.githubusercontent.com/9029654/41297189-9b0ab412-6e2c-11e8-8f62-4b3edb61b1b7.png)

Dependent on https://github.com/graycoreio/daffodil/issues/622

## What is the motivation / use case for changing the behavior?
UI Experience Improvement

## Environment
<pre><code>
Daffodil version: 1.0.0-alpha
</code></pre>

**Comment by vickywane** [comment]
Greetings :wave: 

Can i proceed to work on this ?

**Comment by damienwebdev** [comment]
@vickywane absolutely.

**Comment by vickywane** [comment]
@damienwebdev sorry i wont be able to work on this anymore. I dont have much knowledge on Angular as i more skilled on React. I also thought this was more of a styling fix but on digging deeper i can see it requires some knowledge on Angular. 

My apologies for not taking a closer look before indicating my interest to work on it

**Comment by damienwebdev** [comment]
@vickywane thanks, no worries, I appreciate your interest none the less!

**Comment by vickywane** [comment]
Thank you. 

I would keep on trying to fix this but it might not come so fast
