### ISSUE TITLE
Add animation to the placeholder text of daff-inputs in the design module

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#259]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The placeholder text for inputs are static and boring.

## Expected behavior

![input-animation](https://user-images.githubusercontent.com/15809918/52748979-eb03ed80-2fb5-11e9-9584-03951110b9f2.gif)

## What is the motivation / use case for changing the behavior?
A better UX for daff-design input components

**Comment by xelaint** [comment]
Closed because issue #416 will provide updates for this feature
