### ISSUE TITLE
Add fallbacks for CSS grid styles

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#260]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
CSS grid doesn't apply in IE 11. Components using `grid-gap` will render incorrectly without `grid-template-area`s defined.

## Expected behavior

- [ ] Fallbacks should be added for CSS grid styles, so demo and daffio look ok in IE 11.
- [ ] Update instances where `grid-gap` is used to include `grid-template-area`s, or restructure how `grid` is used.

## What is the motivation / use case for changing the behavior?
So demo and daffio look good in IE 11

Here is a good starting point for fallbacks to css grid styles:
https://rachelandrew.co.uk/css/cheatsheets/grid-fallbacks

And here is a short, relevant article:
https://rachelandrew.co.uk/archives/2017/07/04/is-it-really-safe-to-start-using-css-grid-layout/

**Comment by xelaint** [comment]
https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by damienwebdev** [comment]
I'm closing this since we're no longer going to be supporting IE in the near future and grid styles are acceptable.
