### ISSUE TITLE
Remove dependence on FontAwesome for the design library.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#264]
## I'm submitting a...

<pre><code>
[x] Performance issue
[x] Feature request
</code></pre>

## Current behavior
Currently, we only need the font awesome library in the design package because of:

```
<i class="fas fa-chevron-up daff-accordion-item__icon">
<i class="fas fa-chevron-down daff-accordion-item__icon">
```

We import the full icon font even if we don't need 99.9% of the icons.

## Expected behavior
We only load what we need, in this case, we can probably get away with making our own pure css chevrons.

**Comment by xelaint** [comment]
@damienwebdev We also use FontAwesome icons in demo and daffio. (`fab-github`, `fab-gitter`,  `fa-times`,` fa-bars`, `fa-check`)

**Comment by damienwebdev** [comment]
Yes.
