### ISSUE TITLE
[BUG] The main mobile sidebar for daff.io shows the docs sidebar instead of the main nav info

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2676]
# :bug: Bug report

## Current Behavior
The main mobile sidebar for daff.io shows the docs sidebar instead of the main nav info

## Expected Behavior
The mobile sidebar for daff.io should show the primary nav information instead of the docs sidebar with all the packages. That should be a sidebar that's only shown when navigated to the docs page.

Relates to: #1925 

## Minimal reproduction of the problem with instructions
1. Visit next.daff.io
2. Switch to mobile view
3. Click on the hamburger menu

## What is the motivation / use case for changing the behavior?
We should show the correct information.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by AnnieMi888** [comment]
blocked by #2641

**Comment by AnnieMi888** [comment]
relates to #1925

**Comment by damienwebdev** [comment]
Depends on #2680
