### ISSUE TITLE
[FEAT] Different main nav and sidebars for marketing vs documentation pages on daff.io

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2680]
# :bulb: Feature request

## Feature Name
Different main nav and sidebars for marketing vs documentation pages on daff.io

## The Desired Behavior
The main navigation on the marketing pages should be different from the documentation pages.

Dynamic rendering for main nav and main sidebar.

## Your Use Case
As a designer, I would like to display different information on the main navigation and sidebars on the documentation pages so that users can correctly navigate to the docs they are searching for.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
I don't think secondary outlets are the answer here, I think we should adopt a vue like approach and simply specifiy the components for the additional areas in the data field and dynamically render them with a custom directive/component.
