### ISSUE TITLE
[FEAT] Implement a Daffodil docs nav, separate from the marketing portion of the site

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2681]
# :bulb: Feature request

## Feature Name
Daffodil Docs Navigation

## The Desired Behavior
The docs section of `daff.io` top nav should be different from the marketing page nav. This is the tentative structure of what the top nav and primary sidebar should have:

Top Nav:
- Packages
- Design
- API Index (no left nav required)
- Search field

## Your Use Case
As a Daffodil core developer, I want the `docs.daff.io` navigation to be separate from the marketing page nav.

## Environment

<pre><code>
Daffodil version: 0.66.1
Angular version: 15.2.0

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
Blocked by #336

**Comment by damienwebdev** [comment]
![Image](https://github.com/graycoreio/daffodil/assets/9029654/3cbba653-6d11-4406-8505-5a7f9b10c5df)

**Comment by xelaint** [comment]
This is technically complete since there is a different nav for docs. What's missing is the Design link and search field, which should be handled in separate issues.
