### ISSUE TITLE
[FEAT] Dedicated Daffodil Design System Page on daff.io/docs

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2684]
# :bulb: Feature request

## Feature Name
Daff.io x Design Land

## The Desired Behavior
- [x] UX for the mobile nav
- [x] UX for the mobile sidebar - Mobile sidebar should be the same as Desktop top nav content.
- [x] UX for the desktop nav
- [x] Design Docs Landing Page
- [x] Docs generation

Left nav for Design:
- [x] Getting Started
- [x] Foundations/Guidelines
- [x] Components

## Your Use Case
As a designer and developer, I would like the `@daffodil/design` documentation to be separate from all the other packages in Daffodil. The design system documentation is complex and warrants its own feature page/section.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
@griest024 noticed that the design package link is currently `next.daff.io/design`. Will we be changing it to `next.daff.io/docs/design`?

**Comment by griest024** [comment]
yes
