### ISSUE TITLE
[FEAT] Rename all `OVERVIEW.md` files to `README.md`

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2695]
# :bulb: Feature request

## Feature Name
Rename all `OVERVIEW.md` files to `README.md`

## The Desired Behavior
All markdown files that are titled `OVERVIEW.md` should be renamed to `README.md`

## Your Use Case
As a Daffodil core developer, I would like docs generation to correctly generate the overview docs for each package.

## Environment

<pre><code>
Daffodil version: 0.66.1
Angular version: 15.2.0

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
@damienwebdev There are actually no readme files that are named `OVERVIEW.md` in Daffodil.

**Comment by damienwebdev** [comment]
Awesome!
