### ISSUE TITLE
[FEAT] Add support for description in the `DaffioGuideList` interface

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2717]
# :bulb: Feature request

## Feature Name
Add support for description in the `DaffioGuideList` interface

## The Desired Behavior
The description should pull from the `package.json` description of each package.

Blocked by #2641

## Your Use Case
As a developer, I would like a brief overview of what each Daffodil package is used for.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
closed by #3031
