### ISSUE TITLE
[BUG] URL should be included on package level nodes for docs generation

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2719]
# :bug: Bug report

## Current Behavior
Using main package URLs for the packages overview page. Noticed that packages with child markdown files have a url of `/undefined`

## Expected Behavior
Include the URL on package level nodes.

## Minimal reproduction of the problem with instructions
1. navigate to `next.daff.io/guides` or `next.daff.io/packages` (depending on if certain PRs have been merged)
2. Click on the `@daffodil/cart` card
3. Should redirect to `/404` because the route is `/undefined`

**Comment by damienwebdev** [comment]
This appears corrected. On https://next.daff.io/docs/packages 
![image](https://github.com/graycoreio/daffodil/assets/9029654/a9939630-b5dd-45fd-b3e4-ad369b6625bf)
 works as expected and navigates you to https://next.daff.io/docs/packages/cart
