### ISSUE TITLE
[BUG] Code blocks in article headings are not sized correctly

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2742]
# :bug: Bug report

## Current Behavior
Code blocks in article headings are not sized correctly

<img width="1093" alt="Screen Shot 2024-01-30 at 8 55 14 AM" src="https://github.com/graycoreio/daffodil/assets/15809918/23ed7b6f-656f-4f2b-b750-10fb84b141a4">

## Expected Behavior
Updated article code block styling when it's used in headings

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
@damienwebdev @griest024 Do you guys have an opinion on whether we should:

1. Remove the usage of code blocks in headings
2. Keep the code blocks in headings and add appropriate styling for it

**Comment by griest024** [comment]
I perfer (2)

**Comment by damienwebdev** [comment]
I also prefer 2.
