### ISSUE TITLE
[FEAT] Add visual hierarchy and bottom nav to sidebar component

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#277]
# :bulb: Feature request

## Feature Name
- [x] Sidebar Visual Hierarchy  
- [x] Sidebar Bottom Navigation

## The Desired Behavior
Clearly identify hierarchy in the sidebar nav-items and include an option to add a bottom nav to the sidebar to display useful information.

## Your Use Case
As a designer, I'd like to be able to create a visual hierarchy for the nav items in the sidebar and have the ability to include a bottom nav to display additional information.

## Prior Work
N/A

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@xelaint I don't think the feature name here is unique enough. The goal of "name" is for us to be able to quickly reference the concept posthumously and in regular conversation. "Sidebar Molecule Design Updates" is too generic and doesn't unique describe the feature.

**Comment by xelaint** [comment]
@damienwebdev "Update visual hierarchy and bottom navigation for sidebar molecule" ?

**Comment by damienwebdev** [comment]
@xelaint I updated the issue description with, these should probably be separate PRs:

```
[ ] - Sidebar Visual Hierarchy
[ ] - Sidebar Bottom Navigation
```

**Comment by xelaint** [comment]
@damienwebdev gotcha, can you specify a milestone?
