### ISSUE TITLE
[BUG] Some aspects of demo import code from "libs" as opposed to the built dependencies.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#285]
# :bug: Bug report

## Current Behavior
There are a few examples where "demo" depends on code from the source libraries, as opposed to the built dependencies.

https://github.com/graycoreio/daffodil/blob/develop/apps/demo/src/app/modals/add-to-cart-notification/components/add-to-cart-notification/add-to-cart-notification.component.spec.ts

## Expected Behavior
We should only ever depend on the compiled dependencies.

## What is the motivation / use case for changing the behavior?
Other developers won't be able to repeat the same processes that we use, as they don't have source code in the same repo.

**Comment by lderrickable** [comment]
This was fixed at some point
