### ISSUE TITLE
[FEAT] Add selected functionality for tree component

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2854]
# :bulb: Feature request

## Feature Name
Add selected UI for tree component

## The Desired Behavior
A `[daff-tree-item]` that is active/selected should have a `selected` class added to it to properly style it.

## Your Use Case
As a designer, I would like to indicate to users if a tree item in a tree is currently selected/active.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
use [`routerLinkActive`](https://angular.dev/guide/routing/router-tutorial#identify-the-active-route)

**Comment by xelaint** [comment]
> use [`routerLinkActive`](https://angular.dev/guide/routing/router-tutorial#identify-the-active-route)

@griest024 The styles for `selected` is in the code, but I'm not sure how I can use the `routerLinkActive` directive in `DaffTreeItemDirective` so that a selected tree item has the `routerLinkActive` directive set on it as well.

**Comment by griest024** [comment]
You can assign this to me
