### ISSUE TITLE
[FEAT] Add linting to apps which prevents imports from "libs".

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#286]
# :bulb: Feature request

## Feature Name
Lib Linting

## The Desired Behavior
The demo app should never be allowed to import from "libs", and it should error if it does.

## Your Use Case
See #285 

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xxGizmoCodexx** [comment]
@damienwebdev 
Saw another `hacktoberfest` issue that I thought I could help out with
Please see #2202
