### ISSUE TITLE
[BUG] Brief 404 page error in daff.io/docs when clicking on links

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2965]
# :bug: Bug report

## Current Behavior
Clicking on links that direct to another page in docs causes a brief 404 error. This doesn't happen when navigating around in the tree itself, only when a link is clicked.

https://www.loom.com/share/90a5f8aee38944d1afc40398049f5bc6?sid=88aac3ca-b307-4861-a028-ba25a9fea244

## Expected Behavior
Clicking on a link that routes to an actual page should not display a 404 error page.

## Minimal reproduction of the problem with instructions
1. Go to `/docs/packages/design` or `/docs/packages/forms`
2. Click on any of the links

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
@xelaint I have seen this locally due to messed up local server docs path config. Have you seen this in prod or just locally?

**Comment by xelaint** [comment]
> @xelaint I have seen this locally due to messed up local server docs path config. Have you seen this in prod or just locally?

Just locally. It doesn't happen in next.daff.io
