### ISSUE TITLE
[FEAT] Set up main API page for each package

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2971]
# :bulb: Feature request

## Feature Name
Set up main API page for each package

## The Desired Behavior
Main API page for each package should include a brief description of what the package is along with a comprehensive list of all the available APIs in the package.

## Your Use Case
As a user, I want to see an overview of all the available APIs in a package.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
blocked by #2816

**Comment by xelaint** [comment]
> blocked by #2816

is this a duplicate issue then?

**Comment by griest024** [comment]
no, I think this should track the design and daff.io implementation but the other issue tracks actually generating the correct data with dgeni

**Comment by damienwebdev** [comment]
This depends upon, but is not blocked by #2693
