### ISSUE TITLE
[FEAT] Breadcrumbs on top of docs pages

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2973]
# :bulb: Feature request

## Feature Name
Breadcrumbs on top of docs pages

## The Desired Behavior
There should be breadcrumbs on the top of all docs pages so that a user knows where they are.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Dependent Tasks:
- [x] #3046
- [x] #3021

**Comment by xelaint** [comment]
@griest024 does a `DaffioDocsBreadcrumb` interface need to be created for this to work or can we just use `DaffioDocList`?

**Comment by griest024** [comment]
@xelaint I think we could *technically* use the nav list data to infer the breadcrumb information but this doesn't feel correct. I think we should just add the breadcrumb data to the doc. @damienwebdev thoughts?

**Comment by damienwebdev** [comment]
Yes, we should add the breadcrumb to the doc type, not retrieve it from elsewhere.

**Comment by xelaint** [comment]
Depends on #3021

**Comment by griest024** [comment]
What should the breadcrumb structure be? For a symbol in `@daffodil/cart/driver/magento` should it be `Docs > API > @daffodil/cart > driver > magento > <symbol>` or `Docs > API > @daffodil/cart/driver/magento > <symbol>`?

**Comment by xelaint** [comment]
> What should the breadcrumb structure be? For a symbol in `@daffodil/cart/driver/magento` should it be `Docs > API > @daffodil/cart > driver > magento > <symbol>` or `Docs > API > @daffodil/cart/driver/magento > <symbol>`?

I think `Docs > API > @daffodil/cart > driver > magento > <symbol>` makes more sense?

**Comment by griest024** [comment]
@xelaint Actually I disagree after working on this some more. I think that we should be matching the nesting structure of the sidebar tree with the breadcrumbs. Plus that scheme is way more difficult to implement.

**Comment by xelaint** [comment]
@griest024 Is `@daffodil/cart/driver/magento` an actual package though? I thought the Magento driver was just a feature of `@daffodil/cart`.

**Comment by griest024** [comment]
@xelaint its a real entrypoint. Its a subpackage of `@daffodil/cart`, if that's what you mean

**Comment by damienwebdev** [comment]
@griest024 I agree with @xelaint. It should match, but we also need to defer legibility.

I would imagine that the breadcrumb would look like:

`@daffodil/cart > @daffodil/cart/driver > @daffodil/cart/driver/magento > @daffodil/cart/driver/magento/2.4.1 > SomeToken`

This is rather long to write and will be difficult to read on a mobile device.

**Comment by griest024** [comment]
Should the current breadcrumb also have its label truncated?
1. `@daffodil/cart > driver > @daffodil/cart/driver/magento`
2. `@daffodil/cart > driver > magento`

**Comment by xelaint** [comment]
> Should the current breadcrumb also have its label truncated?
> 
> 1. `@daffodil/cart > driver > @daffodil/cart/driver/magento`
> 2. `@daffodil/cart > driver > magento`

2. `@daffodil/cart > driver > magento`

**Comment by griest024** [comment]
> > Should the current breadcrumb also have its label truncated?
> > 
> > 1. `@daffodil/cart > driver > @daffodil/cart/driver/magento`
> > 2. `@daffodil/cart > driver > magento`
> 
> 2. `@daffodil/cart > driver > magento`

okay the PR currently uses (1) because implementing (2) was a bit trickier than I thought...I will try again
