### ISSUE TITLE
feat(header, nav-bar): Header containing logo, nav-bar, and sub-nav.

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#30]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
A header/nav does not exist for the demo. Additionally, when a product is added to cart, there is no proper place to display a minicart or notification.

## Expected behavior
Header for Daffodil sample store. Header includes logo, navbar with basic nav items, and subnav (sign in, account, cart icons)

Mock + Prototype: https://framer.cloud/aFzwn

## What is the motivation / use case for changing the behavior?
General page structuring and UX Experience Improvement

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@xelaint Can you clarify this feature more into a precise spec? To say "nav" is a fairly broad term which can mean many things. Do you have a sample for us to start with as an initial implementation? I was thinking something along the lines of the sidebar on https://www.walmart.com/?

**Comment by xelaint** [comment]
@damienwebdev updated this feature to only include the header and navbar. I noticed that the styling on certain pages are added without consideration of the header, page container, etc. I will come up with a mock asap so we can get this implementation going.

**Comment by xelaint** [comment]
@damienwebdev Mock + Prototype: https://framer.cloud/aFzwn

**Comment by damienwebdev** [comment]
Resolved in #53
