### ISSUE TITLE
[FEAT] Auto-generate Daffodil package list for markdown files

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3012]
# :bulb: Feature request

## Feature Name
Auto-generate Daffodil package list for markdown files

## The Desired Behavior
Auto-generate the list of Daffodil packages with project name, package name, version, and stability (https://github.com/graycoreio/daffodil?tab=readme-ov-file#packages-)

Write a "generate" command that processes the package.json of all the publishable packages and the spits out content into the markdown file.

## Your Use Case
As a developer, I don't want to have to manually update the list of available Daffodil packages on multiple markdown files.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
Where would this list of packages be displayed?

**Comment by xelaint** [comment]
> Where would this list of packages be displayed?

https://github.com/graycoreio/daffodil?tab=readme-ov-file#packages-

**Comment by griest024** [comment]
But it can be its own file or do we need to embed it in the main README? I think we might need to do this with release please.

**Comment by xelaint** [comment]
I think it needs to be in the main README

**Comment by griest024** [comment]
During planning we decided that the generation should occur during release please cycle.

**Comment by griest024** [comment]
Although release please does have some kind of plugin system, loading custom plugins is janky, nigh impossible with the GH action. See https://github.com/ipfs-shipyard/release-please-ipfs-plugin for an example

**Comment by damienwebdev** [comment]
Try to modify https://github.com/graycoreio/daffodil/blob/develop/.github/workflows/release-please.yml before release-please runs to see if it will add your changes to the diff release-please submits.

**Comment by griest024** [comment]
> Try to modify https://github.com/graycoreio/daffodil/blob/develop/.github/workflows/release-please.yml before release-please runs to see if it will add your changes to the diff release-please submits.

That doesn't work unfortunately. The only other solution I can see is to ditch the action and run using the CLI. Either that or wait until google lets us load plugins with the action.

**Comment by xelaint** [comment]
@griest024 Should I just manually update the list of packages for now then?

**Comment by damienwebdev** [comment]
@griest024 Try a task afterwards of the action to take the result branch, modify the README and push to the same branch as release-please.
