### ISSUE TITLE
[FEAT] Deprecate `<daff-nav-list>` in favor of `<daff-tree>`

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3022]
# :bulb: Feature request

## Feature Name
Deprecate <daff-nav-list> in favor of <daff-tree>

## The Desired Behavior
`<daff-nav-list>` is no longer needed as we have the option to use a flat `<daff-tree>`

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This should not be deprecated. 

See the MDN guide on tree:

> ARIA tree views are navigated primarily with arrow keys on the keyboard instead of the Tab. This form of navigation is not common for most browser content, though normal and expected for native applications. For this reason, before creating a tree view, consider alternative options to address the functionality you need.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role#see_also
