### ISSUE TITLE
[BUG] Sidebar content on API, packages, and guides are not visible on server side render

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3059]
# :bug: Bug report

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This requires resolvers (building upon https://github.com/graycoreio/daffodil/issues/3135)
