### ISSUE TITLE
[FEAT] Only display the relevant root package tree in the sidebar of a type page

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3064]
# :bulb: Feature request

## The Desired Behavior
Only display a type's root package tree

i.e. If a user is on `/docs/api/auth/testing/MockAccountRegistration`, the sidebar should only display `@daffodil/auth` information instead of every API reference.

This is to reduce overcrowding of the sidebar.

<img width="1408" alt="Screen Shot 2024-09-12 at 1 36 39 PM" src="https://github.com/user-attachments/assets/1648da84-dd98-4441-a3eb-8f8ba1e18afd">

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
I don't think this is the correct thing to do. Instead, I think we should implement some kind of "child panes" for the package list sidebar like angular.dev does.

E.g. https://i.imgur.com/ui5PVCU.mp4

**Comment by xelaint** [comment]
Okay, let me play around with designs.

**Comment by griest024** [comment]
blocked by #3304

**Comment by damienwebdev** [comment]
@xelaint discussed this and this is no longer a requirement.

**Comment by xelaint** [comment]
Closed in favor of #3346
