### ISSUE TITLE
[BUG] `@Output` properties are displayed incorrectly in API docs

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3173]
# :bug: Bug report

## Current Behavior
`@Output` properties are displayed incorrectly in API docs

<img width="1084" alt="Screen Shot 2024-10-09 at 9 57 51 AM" src="https://github.com/user-attachments/assets/8668c450-685d-49f8-ac9d-fbfb457a807b">

They are nested inside the `<tbody>` of the previous `@Input`

## Expected Behavior
Output properties should be displayed sibling to any other properties, not as a child property.

## Minimal reproduction of the problem with instructions
View next.daff.io/docs/design/api/notification/DaffNotificationComponent

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
We acknowledge that this bug is real, but the work to fix this is unnecessary and is being replaced by 
 https://github.com/graycoreio/daffodil/issues/3306
