### ISSUE TITLE
[BUG] The daff.io "contact" page's button is mis-aligned.

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#325]
# :bug: Bug report

## Current Behavior
Currently the daff.io's contact page button is mis-aligned.
<img width="1342" alt="Screen Shot 2019-03-20 at 10 45 35 AM" src="https://user-images.githubusercontent.com/9029654/54693802-9a743880-4afd-11e9-9c3a-05ad8427f21c.png">

## Expected Behavior
The button is aligned properly.

## Minimal reproduction of the problem with instructions
1. Load up the daff.io site
2. visit `/support`
3. See button mis-aligned.

## What is the motivation / use case for changing the behavior?
Sanity.

**Comment by lderrickable** [comment]
How do I reproduce this bug? I'm not seeing it. Tried different screensizes and chrome and safari.

**Comment by damienwebdev** [comment]
@lderrickable I see it here: https://daffio-bygtlvnw3.now.sh/support
