### ISSUE TITLE
[FEAT] Don't inject factories in root

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#329]
# :bulb: Feature request

## Feature Name
Don't inject factories in root.

## The Desired Behavior
Factories shouldn't be injected in root, because they aren't needed throughout the entire testing suite.

## Your Use Case
As a developer, I want my tests to run as quickly and efficiently as possible

## Prior Work
N/A

**Comment by damienwebdev** [comment]
In retrospect, factories should be injectable from the root. I'll leave this open as we need to back any existing factories to the root.

**Comment by griest024** [comment]
Can this be closed?

**Comment by damienwebdev** [comment]
@griest024 we'd need to audit all existing factories to ensure that they are provided correctly.

**Comment by lderrickable** [comment]
I checked all factories. All are injected in root
