### ISSUE TITLE
[FEAT] Sidebar pane design for subpackage information in docs sidebar

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3304]
# :bulb: Feature request

## Feature Name
Sidebar pane design for subpackage information in docs

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This is no longer necessary.
