### ISSUE TITLE
[FEAT] Standardized Deprecation Protocol

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#3305]
# :bulb: Feature request

## Feature Name

Standardized Deprecation Protocol

## The Desired Behavior

- [x] #3318
- [x] #3319
- [x] #3320

## Your Use Case

As an app dev, I want to know when a symbol will be removed.
As a maintainer, I don't want to forget to remove deprecated symbols.

**Comment by griest024** [comment]
@damienwebdev So 3 minor versions in pre-release? How about post v1, every major?

**Comment by damienwebdev** [comment]
@griest024 that strategy sounds good!
