### ISSUE TITLE
[FEAT] Adding a new component should be sufficient in auto generating daff.io design nav tree

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#3315]
# :bulb: Feature request

## Feature Name
Adding a new component should be sufficient in auto generating daff.io design nav tree

## The Desired Behavior
Should not have to manually add component name to index.json file for it to generate in the nav tree.

https://github.com/graycoreio/daffodil/actions/runs/11558259883/job/32170200535

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by griest024** [comment]
Specifically referencing every single guide for a hardcoded nav list was an explicit feature request. @damienwebdev can you weigh in?

**Comment by damienwebdev** [comment]
I think that everything else except components should be encoded in the index.json files. I don't think components have any inherent ordering beyond alphabetical, so I don't see a need for them to be manually managed like other kinds of guides.

**Comment by griest024** [comment]
Okay I will adjust the implementation to these new requirements
