### ISSUE TITLE
[FEAT] Run dgeni with `tsx`

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#3325]
# :bulb: Feature request

## Feature Name

Run dgeni with `tsx`

## The Desired Behavior

Dgeni should be run with `tsx`, not `ts-node`

## Your Use Case

As a maintainer, I want to interface with daffodil packages from dgeni and docs-utils.

**Comment by griest024** [comment]
blocked by dgeni using black magic to DI based on stringified functions. TSX will use arrow functions under the hood so dgeni's regex for finding function params doesn't work.

**Comment by damienwebdev** [comment]
Closing as it appears that this is not possible. In order to do this, we need to replace degni with a typescript friendly docs-gen system.
