### ISSUE TITLE
[FEAT] SSR Image Preloading via Header

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#3340]
# :bulb: Feature request

## Feature Name

SSR Image Preloading via Header

## The Desired Behavior

I want a service that allows me to add [image preload link headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) to the SSR document reponse.

## Your Use Case

As an app dev, I'd like to be able to specify important, LCP-impacting images in various priorities.

**Comment by griest024** [comment]
@damienwebdev opinions on package name? I prefer `@daffodil/ssr` as it aligns with angular.

**Comment by damienwebdev** [comment]
Agreed!

**Comment by griest024** [comment]
@damienwebdev is it okay to type the tokens as specifically *express* `Request` and `Response` or should we leave it open to multiple server frameworks?

**Comment by damienwebdev** [comment]
I think that we should leave it open. Express could be replaced eventually
