### ISSUE TITLE
[BUG] Design components overview page will occasionally show no components

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#3347]
# :bug: Bug report

## Current Behavior

Occasionally, I'll see a page like: 

![image](https://github.com/user-attachments/assets/e280bc5a-bdf0-4f06-b523-8dbc6711c367)

There is also a console error saying failed trying to access "children" of undefined.

## Expected Behavior
This should not error.

## Minimal reproduction of the problem with instructions
This is hard to reproduce, but it happens when you the visit page.

**Comment by griest024** [comment]
related to #3327.

a consistent repro is:
1. refresh page that is outside of the design routes, e.g. `/docs/api`
2. navigate to `/docs/design/components` by using the UI, not the address bar
