### ISSUE TITLE
[FEAT] $body-font-family as an assignable variable

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#371]
# :bulb: Feature request

## Feature Name
Allow `$body-font-family` to be an assignable variable

## The Desired Behavior
`$body-font-family` should be assignable so that when @daffodil/design is used, users can assign their brand font to `$body-font-family`.

https://thoughtbot.com/blog/sass-default

## Your Use Case
As a user, I should be able to specify my own `$body-font-family`.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This should probably be brought into a Design Token. #1880

**Comment by xelaint** [comment]
@damienwebdev Closing this issue. Merged this with #1880
