### ISSUE TITLE
[FEAT] Quotemark Linting Rule

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#424]
# :bulb: Feature request

## Feature Name
Quotemark Linting Rule

## The Desired Behavior
https://palantir.github.io/tslint/rules/quotemark/

Enforce `single` argument.

## Your Use Case
As a developer, I'd like the codebase to use single quote marks.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by LoganArnett** [comment]
Can you assign this to me?
