### ISSUE TITLE
feat(mini-cart): Display a detailed notification when products are added to cart.

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#43]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no header to display cart icon or the option to quickly view what is in cart.

## Expected behavior
Cart notification will appear when a product is added to the cart.

Mock + Prototype: https://framer.cloud/aFzwn

## What is the motivation / use case for changing the behavior?
General page structuring and UX Experience Improvement. 

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
Mock + prototype: https://framer.cloud/aFzwn

**Comment by xelaint** [comment]
Mobile Mock + Protoype: https://framer.cloud/cKTSv
![demo-store-mobile 2x](https://user-images.githubusercontent.com/15809918/46293486-a70dd000-c561-11e8-911d-9d9cbdc338c1.jpg)

**Comment by lderrickable** [comment]
Implemented here: https://github.com/graycoreio/daffodil/pull/97
