### ISSUE TITLE
[DOCS] Paginator Documentation

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#469]
# :page_facing_up: Documentation Request

## What were you doing?
There is no docs file in `@daffodil/design` for `daff-paginator`.

## Expected behavior
Write documentation for the `daff-paginator` component.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This was documented during https://github.com/graycoreio/daffodil/commit/b5338a0d3cf1cb33a3cc8c5219673f7925a75387
