### ISSUE TITLE
Feature Request: Thank you page after completing a checkout successfully

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#48]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, once you complete a checkout, nothing happens.

## Expected behavior
After completing a checkout successfully, I'm redirected to a thank you page.

Mock: https://app.zeplin.io/project/5a73de4c805b1892322d9275/screen/5b7c4207d77a451b52ae0ef4

## What is the motivation / use case for changing the behavior?
User Experience/Version 1.0 Requirements

**Comment by xelaint** [comment]
Thank you page mock added to Zeplin.

**Comment by damienwebdev** [comment]
@xelaint the zepplin instance isn't open -source can you change it to framer so that if can be publicly view historically?

**Comment by lderrickable** [comment]
Being addressed here: https://github.com/graycoreio/daffodil/pull/61
