### ISSUE TITLE
Going to checkout page redirects to a different url depending on driver configuration

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#49]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Clicking "Continue to Checkout" always routes the user to the daffodil checkout page.

## Expected behavior

When using the Shopify driver, the user should be routed to the appropriate Shopify checkout page.

**Comment by lderrickable** [comment]
Being addressed here: https://github.com/graycoreio/daffodil/pull/63.

**Comment by damienwebdev** [comment]
This is handled by our new payment drivers and their package implementations. For Shopify payments, we would just use a redirect process like we do with PayPal.
