### ISSUE TITLE
Feature Request: Foundation-Demo Footer 

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#50]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
There's no footer.

## Expected behavior
I want a footer to be able to click around the application.

## What is the motivation / use case for changing the behavior?
User experience/navigation.

**Comment by xelaint** [comment]
Mock added to: https://framer.cloud/aFzwn

**Comment by lderrickable** [comment]
Was addressed here: https://github.com/graycoreio/daffodil/pull/56
