### ISSUE TITLE
Feature Request: Foundation Demo 404 Page

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#51]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by xelaint** [comment]
![demo-store 404 2x](https://user-images.githubusercontent.com/15809918/44424946-9462ad00-a558-11e8-9259-2352ea8066f2.jpg)

**Comment by lderrickable** [comment]
Being addressed here: https://github.com/graycoreio/daffodil/pull/58
