### ISSUE TITLE
[FEAT] Add support for Magento 2 GraphQL Guest Cart Driver

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#537]
# :bulb: Feature request

## Feature Name
Magento 2 Rest Cart Driver

## The Desired Behavior
We'd add a Magento 2 driver that implements [the cart interface](https://github.com/graycoreio/daffodil/blob/develop/libs/cart/src/drivers/interfaces/cart-service.interface.ts) and makes API requests to add items to/from a given cart.

## Your Use Case
As a user, I'd like to be able to add items to my cart if my ecommerce platform of choice is Magento 2.

## Prior Work
Here's the Magento 2 tutorial for the [REST API for cart](https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-config-store.html).

Here's the [API Docs](https://devdocs.magento.com/redoc/2.3/guest-rest-api.html#tag/guest-carts)

**Comment by damienwebdev** [comment]
@griest024

**Comment by griest024** [comment]
@damienwebdev Why shouldn't I use the GraphQL API for this driver? Does it not support guest carts?

**Comment by damienwebdev** [comment]
Last I checked with the team at Magento, the GraphQL implementation isn't quite ready yet.

**Comment by griest024** [comment]
Okay. I only ask because the Magento product driver uses GraphQL.

**Comment by griest024** [comment]
Closing because this was addressed.
