### ISSUE TITLE
(refactor): Shipping Form and Address-form into separate components

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#54]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Refactor
</code></pre>

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
This is being completed as part of https://github.com/graycoreio/daffodil/pull/45
