### ISSUE TITLE
(refactor): page loading animations to a more consistent design

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#55]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: refactor
</code></pre>

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
This was completed in the fix minor bugs pull request
