### ISSUE TITLE
Feature Request: Update Font Awesome Version

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#60]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Current Font Awesome version is at v5.0.13

## Expected behavior
Update to current version, v5.3.1
https://fontawesome.com/changelog/latest

## What is the motivation / use case for changing the behavior?
Access to latest version of icons

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
Being addressed in https://github.com/graycoreio/daffodil/pull/62

**Comment by xelaint** [comment]
This was completed in #62.
