### ISSUE TITLE
[BUG] DaffCartItem `description` is not defined.

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#740]
# :bug: Bug report

## Current Behavior
`description` is not defined in DaffCartItem. It is needed to add secondary information to cart items.

## Expected Behavior
`description: string;` should be added back to DaffCartItem.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
CartItems don't have a description. There may be other properties like "color" and "size" that are applicable for a given cart item, but `description` does quite fit this.

We will likely need to handle product type variance across the different DaffProduct types to properly accomodate this.
