### ISSUE TITLE
Feature Request: Off-Canvas Container

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#76]
## I'm submitting a...
[x] Feature request

## Current behavior
Currently, there is no component to address off-canvas containers that can slide into the viewport when activated.

## Expected behavior
Off canvas container outside of the viewport that slides in when activated. (i.e., when a product is added to cart on mobile, the off canvas container slides in from the bottom)

## Minimal reproduction of the problem with instructions

```<div class="off-canvas"></div>```

variants to determine what position the container slides in from: `position-left`, `position-right`, `position-top`, `position-bottom`

## What is the motivation / use case for changing the behavior?
Useful for mobile and desktop to display notifications.

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
I believe this is addressed by #86, closing.
