### ISSUE TITLE
Feature Request: Create a Daffodil Mini Site

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#78]
## I'm submitting a...

[x] Feature request

## Current behavior
There is currently no mini site for Daffodil to promote and explain the purpose of Daffodil.

## Expected behavior
A mini site for Daffodil to educate users about the purpose of Daffodil and promote it to marketing managers, designers, and developers.

## Minimal reproduction of the problem with instructions
![home 2x](https://user-images.githubusercontent.com/15809918/46414222-a5264700-c6f0-11e8-84a8-3cbef981eb14.jpg)
![pwa page 2x](https://user-images.githubusercontent.com/15809918/46414296-d56de580-c6f0-11e8-8bb8-99659316a3ed.jpg)

## What is the motivation / use case for changing the behavior?
To promote Daffodil.

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by xelaint** [comment]
Partially complete in #90

**Comment by damienwebdev** [comment]
Some more was added to this in #171

**Comment by damienwebdev** [comment]
#167 also addresses this -- but we'll need a little more work to get this continuously deployed.
