### ISSUE TITLE
Feature Request: Nested Menu

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#79]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
Currently, there is no design for a nested menu for the sidebar nav.

## Expected behavior
Desktop: https://framer.cloud/aFzwn
Mobile: https://framer.cloud/cKTSv

## What is the motivation / use case for changing the behavior?
Add a nested menu option.

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This is covered by #429
