### ISSUE TITLE
[FEAT] DaffCardComponent Types

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#805]
# :bulb: Feature request

## Feature Name
DaffCardComponent Types

## The Desired Behavior
DaffCardComponent should have three types: `raised`, `stroked`, and `flat`. It should be implemented similarly to `DaffButtonComponent`

## Your Use Case
As an enduser, I'd like to be able to use different styles of a card.

## Prior Work
Referencing DaffButtonComponent's type implementation.

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@xelaint can you follow up on this?
