### ISSUE TITLE
Feature Request: Update Typography

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#85]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior
`<h1>` to `<h6>` are not styled, and we are currently constrained to only 3 font size variables.

## Expected behavior
Styles set for `<h1>` to `<h6>` and update current font size variables / update font sizes throughout the pages.

## What is the motivation / use case for changing the behavior?
Organize typography

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@xelaint can review this issue. I seems misformatted.

**Comment by xelaint** [comment]
> @xelaint can review this issue. It seems misformatted.

fixed.

**Comment by xelaint** [comment]
Addressed here: #91
