### ISSUE TITLE
[FEAT] Using factories inside of other factories

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#882]
# :bulb: Feature request

## Feature Name
Using factories inside of other factories

## The Desired Behavior
We would like to be able to use factories inside of other factories to decrease code duplication. A good example of where this would be useful is in the `DaffConfigurableProductFactory`.

## Your Use Case
As a developer, I should be able to use a factory to new up part of another factory.

**Comment by damienwebdev** [comment]
@lderrickable in review, is there any reason that this isn't possible today?

**Comment by griest024** [comment]
This is possible inside a private method. Closing in favor of #1214
