### ISSUE TITLE
[BUG] CartLoadFailure error thrown when CartNotFoundError should be thrown

### ISSUE THREAD

**Issue by lderrickable** [graycoreio/daffodil#936]
# :bug: Bug report

## Current Behavior
When the magento driver.get cart is called with a bad id, it seems the error thrown is a DaffCartLoadFailure instead of a DaffCartNotFoundError. This messes up the cart resolver effects, which would usually fire off a DaffCartCreate action whenever this occurs. 

## Expected Behavior
The DaffCartNotFoundError should be thrown instead.

## Minimal reproduction of the problem with instructions
Run Demo app. Change the cart id in local storage to something that doesn't exist in the backend. refresh the page using the DaffCartResolve action in conjunction with the DaffCartResolverEffects.

## What is the motivation / use case for changing the behavior?
A user with a bad cart id in local storage will never be able to use the app.

**Comment by griest024** [comment]
The resolver behavior has changed significantly and I don't this issue is still relevant.
