### ISSUE TITLE
[FEAT] Design Land Example Viewer UI

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#944]
# :bulb: Feature request

## Feature Name
Design Land Example Viewer UI

## The Desired Behavior
Update the UI for Design Land's Example Viewer so documentation is aesthetically pleasing. The functional aspect of the example viewer has been completed. 

## Your Use Case
As a developer, I'd like the component docs to be easy to view. 

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
This is partially complete @xelaint and only needs some styling to make it more palettable.
