### ISSUE TITLE
Daff-Sidebar z-index issues

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#98]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
</code></pre>

## Current behavior
<img width="1440" alt="screen shot 2018-10-16 at 3 59 03 pm" src="https://user-images.githubusercontent.com/9029654/47043840-ad549c80-d15c-11e8-9c67-595262fff16f.png">
<img width="1440" alt="screen shot 2018-10-16 at 3 59 00 pm" src="https://user-images.githubusercontent.com/9029654/47043841-ad549c80-d15c-11e8-8f95-fe337b7796b6.png">

## Expected behavior
In previous versions of `daff-sidebar` the backdrop covered elements in `daff-sidebar-content` elements.

## Minimal reproduction of the problem with instructions
1. Click on sidebar on developer

## What is the motivation / use case for changing the behavior?
It's annoying.

## Environment
Daffodil version: 6ecf14b78c65ffb9349af4bf884862072bc21318

**Comment by lderrickable** [comment]
Being addressed here: https://github.com/graycoreio/daffodil/pull/101
